Using TensorFlow backend.


In [2]:
import numpy as np

# 랜덤시드 고정시키기
np.random.seed(3)

from keras.preprocessing.image import ImageDataGenerator

# 데이터셋 불러오기
train_datagen = ImageDataGenerator(rescale=1./255, 
                                   rotation_range=10,
                                   width_shift_range=0.2,
                                   height_shift_range=0.2,
                                   shear_range=0.7,
                                   zoom_range=[0.9, 2.2],
                                   horizontal_flip=True,
                                   vertical_flip=True,
                                   fill_mode='nearest')

train_generator = train_datagen.flow_from_directory(
        './handShape/train',
        target_size=(24, 24),
        batch_size=3,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        './handShape/test',
        target_size=(24, 24),    
        batch_size=3,
        class_mode='categorical')

Using TensorFlow backend.


Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D

from keras.layers import Dropout

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))

# 모델 엮기
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# 모델 학습시키기
# Use fit_generator when using ImageGenerator
# Should Install PIL(Pillow)
model.fit_generator(
        train_generator,
        steps_per_epoch=15 * 100,
        epochs=200,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/200
1500/1500 [==============================] - 34s 23ms/step - loss: 0.4069 - acc: 0.8342 - val_loss: 0.2868 - val_acc: 0.9333
Epoch 2/200
1500/1500 [==============================] - 36s 24ms/step - loss: 0.1143 - acc: 0.9627 - val_loss: 3.7662e-04 - val_acc: 1.0000
Epoch 3/200
1500/1500 [==============================] - 34s 23ms/step - loss: 0.0775 - acc: 0.9749 - val_loss: 0.3372 - val_acc: 0.9333
Epoch 4/200
1500/1500 [==============================] - 35s 23ms/step - loss: 0.0642 - acc: 0.9767 - val_loss: 0.0330 - val_acc: 1.0000
Epoch 5/200
1500/1500 [==============================] - 35s 23ms/step - loss: 0.0508 - acc: 0.9838 - val_loss: 0.0176 - val_acc: 1.0000
Epoch 6/200
1500/1500 [==============================] - 27s 18ms/step - loss: 0.0490 - acc: 0.9842 - val_loss: 0.0212 - val_acc: 1.0000
Epoch 7/200
1500/1500 [==============================] - 27s 18ms/step - loss: 0.0307 - acc: 0.9884 - val_loss: 0.0545 - val_acc: 1.0000
Epoch 8/200
1500/1500 [==============

In [ ]:
# 모델 평가하기
print("-- Evaluate --")

scores = model.evaluate_generator(
            test_generator, 
            steps = 5)

print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))


In [ ]:
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot

%matplotlib inline

SVG(model_to_dot(model, show_shapes=True).create(prog='dot', format='svg'))


In [ ]:
# 모델 예측하기
print("-- Predict --")

output = model.predict_generator(
            test_generator, 
            steps = 5)

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

print(output)

In [6]:
# Use fit_generator when using ImageGenerator
# Should Install PIL(Pillow)
model.fit_generator(        train_generator,
        steps_per_epoch=15,
        epochs=50,       validation_data=test_generator,
        validation_steps=5)


Epoch 1/50
15/15 [==============================] - 1s 82ms/step - loss: 1.3511 - acc: 0.4889 - val_loss: 1.0340 - val_acc: 0.6667
Epoch 2/50
15/15 [==============================] - 0s 32ms/step - loss: 0.9009 - acc: 0.6444 - val_loss: 0.8083 - val_acc: 0.5333
Epoch 3/50
15/15 [==============================] - 0s 29ms/step - loss: 0.4260 - acc: 0.8889 - val_loss: 0.5792 - val_acc: 0.8667
Epoch 4/50
15/15 [==============================] - 0s 25ms/step - loss: 0.1352 - acc: 0.9778 - val_loss: 0.7112 - val_acc: 0.8000
Epoch 5/50
15/15 [==============================] - 0s 28ms/step - loss: 0.0265 - acc: 1.0000 - val_loss: 0.5701 - val_acc: 0.8000
Epoch 6/50
15/15 [==============================] - 0s 22ms/step - loss: 0.0179 - acc: 1.0000 - val_loss: 0.5554 - val_acc: 0.8667
Epoch 7/50
15/15 [==============================] - 0s 22ms/step - loss: 0.0068 - acc: 1.0000 - val_loss: 0.6160 - val_acc: 0.8667
Epoch 8/50
15/15 [==============================] - 0s 23ms/step - loss: 0.0023 - a

In [7]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))


-- Evaluate --
acc: 86.67%


In [8]:
# Prediction When using ImgGen-
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)


-- Predict --
{'tri': 2, 'rect': 1, 'circ': 0}
[[0.155 0.845 0.000]
 [0.000 0.002 0.998]
 [0.966 0.034 0.000]
 [0.025 0.975 0.000]
 [1.000 0.000 0.000]
 [0.928 0.072 0.000]
 [0.000 0.017 0.983]
 [0.000 0.000 1.000]
 [0.001 0.999 0.000]
 [0.000 0.000 1.000]
 [0.990 0.010 0.000]
 [0.000 0.000 1.000]
 [0.966 0.034 0.000]
 [0.990 0.010 0.000]
 [0.000 0.000 1.000]]
